import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Menu from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          {/* <img src="images/logo.webp"/> */}
          <Image src={"/images/logo.webp"} width={320} height={60} alt="Logo UTI"/>
        </header>
        
        {/* panggil fungsi component navbar(Menu) */}
        <Menu />

        <main className="content">
          {children}
        </main>
        <footer>Copyright &copy; 2026 - TI 24 A</footer>
      </body>
    </html>
  );
}
